# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c42a79f0842355f91b31d0d95e1ea2cc46a2984ff05ff6fc3ee574a84d7ea0120729e55e41aea915a24f8ff0cc00e266cdc1790d73c725a7acda5a37e839abd4

test:
  secret_key_base: ab259503031dc54e79e9413b08d1b351b88250a90193f40e64e74da9820757c8327b01b2b632fd84468dc00c34dea7cad331782c9f314482ed4db35a1c547fdb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
